server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
#        cors-configurations:
#          '[/**]':
#            allowedOrigins: "http://localhost:4200/*"
#            allowedHeaders: "*"
#            allowedMethods:
#              - GET
#              - POST
      routes:
        - id: courseProviderModule
          uri: lb://COURSE-PROVIDER-SERVICE
          predicates:
            - Path=/cps/**
          filters:
            - name: Hystrix
              args:
                name: fallbackCommand
                fallbackUri: forward:/fallback/message
        - id: studentModule
          uri: lb://STUDENT-SERVICE
          predicates:
            - Path=/sts/**
          filters:
            - name: Hystrix
              args:
                name: fallbackCommand
                fallbackUri: forward:/fallback/message
        - id: smsModule
          uri: lb://SUBSCRIPTION-MANAGEMENT-SERVICE
          predicates:
            - Path=/sms/**
          filters:
            - name: Hystrix
              args:
                name: fallbackCommand
                fallbackUri: forward:/fallback/message